### ISSUE TITLE
retryStrategy.retry is not a function

### ISSUE THREAD

**Issue by tedyu** [smithy-lang/smithy-typescript#1084] opened 2023-11-22 21:30 UTC
For aws-sdk-js-v3, we use the following code:
```
const s3 = new S3Client({
  retryStrategy: Util.retryParams,
```
where `retryParams` is defined as:
```
const { ConfiguredRetryStrategy } = require('@smithy/util-retry');

const MAX_RETRIES = 3;
const retryParams = () => new ConfiguredRetryStrategy(
  MAX_RETRIES,
  (retryCount) => {
    return 1000;
  }
);
```
However, at runtime, we see the following stack trace:
```
ERROR   {
  err: TypeError: retryStrategy.retry is not a function
      at /var/task/node_modules/@smithy/middleware-retry/dist-cjs/retryMiddleware.js:58:30
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /var/task/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:63:20
      at async /var/task/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-endpoint-middleware.js:14:24
      at async /var/task/node_modules/@aws-sdk/middleware-sdk-s3/dist-cjs/region-redirect-middleware.js:9:20
      at async /var/task/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:7:26
```
`@smithy/util-retry` 2.0.4 is used.
@aws-sdk/client-s3 3.430 is used.

**Comment by kuhe** [comment] 2023-12-01 15:23
duplicate of https://github.com/aws/aws-sdk-js-v3/issues/5519

**Closed by kuhe** 2023-12-01 15:23 UTC
